# Generated by Django 4.0.4 on 2022-05-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_id_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='nullable',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
